# Generated by Django 5.0.1 on 2024-02-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=100)),
                ("detail", models.TextField(blank=True, null=True)),
                ("reply", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TrackingInfo",
            fields=[
                (
                    "tracking_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("cust_name", models.CharField(max_length=200)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("00", "00 -  รับทราบคำสั่งซื้อ"),
                            ("10", "10 -  บรรจุสินค้า"),
                            ("20", "20 -  รอขนส่งมารับ"),
                            ("30", "30 -  อยู่ระหว่างขนส่ง"),
                            ("40", "40 - ถึงสถานีกระจายสินค้าปลายทาง"),
                            ("50", "50 -  ออกนำส่งให้ผู้รับ"),
                            ("60", "60 -  ส่งสำเร็จ"),
                            ("70", "70 -  ส่งไม่สำเร็จ"),
                            ("80", "80 -  ยกเลิกคำสั่งซื้อ"),
                        ],
                        default=("00", "00 -  รับทราบคำสั่งซื้อ"),
                    ),
                ),
            ],
        ),
    ]
