# Generated by Django 5.0.1 on 2024-03-02 16:01

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=100)),
                ("lname", models.CharField(max_length=100)),
                ("bdate", models.DateField()),
                ("addr", models.TextField()),
                (
                    "tel",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="trackinginfo",
            name="tracking_id",
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
