# Generated by Django 5.0.1 on 2024-05-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_caseinfo_alter_trackinginfo_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinginfo',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remark'),
        ),
    ]
